### ISSUE TITLE
How to build toolchain usable with Arduino?

### ISSUE THREAD

**Issue by M-Reimer** [earlephilhower/esp-quick-toolchain#17]
Hello,

I've found your repository while searching for a way to create a GCC 10.2 toolchain for the ESP8266.

All the repos, I found so far, only build a 4.8 version of GCC and Arduino uses techniques which require a more recent GCC release. I know that I could just use the binaries provided by esp8266.com, but I would prefer to compile my own toolchain.

Can you give a short example how to trigger a build for GCC 10.2? What are the "REL" and "SUBREL" parameters meant for? Do I need docker if I only build for my local machine?

**Comment by earlephilhower** [comment]
Just follow the readme, that's what I do since I can never remember it.  Clone, make download (takes a long time 1st pass), and make.

The REL and SUBREL are only if you care about uploading it (i.e. that will become the generated GH release name it will create on `make upload`).  No Docker needed if you're just doing a Linux make.  Good luck!
